### ISSUE TITLE
Additional class abilities

### ISSUE THREAD

**Issue by ckaotik** [Phanx/MountMe#1]
It would be great to support additional movement buffs other than druid and shaman forms.

The level 60 Warlock talent [Burning Rush](http://www.wowhead.com/spell=111400) provides a 50% movement speed buff until the player's health runs out. (talent id: 19291, spell id: 111400)
Another example would be the Paladin's level 15 talent [Speed of Light](http://www.wowhead.com/spell=85499) which provides a 70% speed bonus for 8 seconds. (talent id: 17565, spell id: 85499)

**Comment by Phanx** [comment]
I thought about trying to support Burning Rush since warlock is my main class these days, but decided against it at some point... though now that I'm thinking about it, I don't remember exactly why, and none of the explanations I can come up with make any sense. I'll think about it some more.

**Comment by Phanx** [comment]
Alright, I still haven't figured out why I didn't want to include Burning Rush, so I've added experimental support for both it and Speed of Light, though I don't have a paladin so I can't guarantee it works, even though I'm pretty sure it should. Since Speed of Light is a cooldown, it requires using the travel form override modifier (default CTRL/STRG, can change at the top of the file).

Any other such abilities you think I should add?

I don't know how I should handle Dash/Stampeding Roar for druids or Spirit Walk for shamans, or even if I should handle them at all. For example, if a shaman presses the button while running, right now it'll activate Ghost Wolf. If he presses it again, should it activate Spirit Walk or cancel Ghost Wolf? When should Spirit Walk be activated without Ghost Wolf? The druid abilities/forms are even more complicated.

**Comment by ckaotik** [comment]
I wouldn't add Stampeding Roar or Spirit Walk either since those are too situational. You don't blow a 2-3min cooldown just "to quickly get away". Situational abilities should not be added, I think.
My gut feeling is this addon is for *things that make me move faster that I can toggle on/off*. Extending this to *... and things with very short cooldowns* lets me add for example Speed of Light.

I've listed some movenent-related spells below, but aren't quite sure which of those should be used by the addon. This list is in no way complete but already shows the amount of spells out there...
### Situational (for the record)
- Shaman: [Spiritwalker's Grace](http://www.wowhead.com/spell=79206)
- Mage: [Icy Floes](http://de.wowhead.com/spell=108839), [Blink](http://www.wowhead.com/spell=1953)
- Druid: [Displacer Beast](http://www.wowhead.com/spell=102280) (a blink), [Wild Charge](http://www.wowhead.com/spell=102401)
- Hunter: [Aspect of the Fox](http://www.wowhead.com/spell=172106), [Disengage](http://www.wowhead.com/spell=781)
- Goblin racial [Rocket Jump](http://www.wowhead.com/spell=69070)

### Movement
- Rogue maybe [Sprint](http://www.wowhead.com/spell=2983)
- Mage: [Blazing Speed](http://www.wowhead.com/spell=108843)
- Druid: [Travel Form](http://www.wowhead.com/spell=783), [Cat Form](http://www.wowhead.com/spell=768) when inside
- Shaman: [Ghost Wolf](http://www.wowhead.com/spell=2645)
- Warlock: [Burning Rush](http://www.wowhead.com/spell=111400)
- Paladin: [Speed of Light](http://www.wowhead.com/spell=85499)
- Death Knight: [Unholy Presence](http://www.wowhead.com/spell=48265) which must toggle back to the previously selected stance, [Death's Advance](http://www.wowhead.com/spell=96268) (talent, when triggered)
- Monk: [Roll](http://www.wowhead.com/spell=109132) (also works with Chi Torpedo)
- Priest: [Power Word: Shield](http://www.wowhead.com/spell=17) with [Body and Soul](http://www.wowhead.com/spell=64129)

**Comment by Phanx** [comment]
Yeah, I was always annoyed by Squire2's configuration too, and when WoD hit it wasn't obvious that Squire3 existed (there was no link from the old page) so I started writing my own. I did try Squire3 but it had the same bugs with shaman Ghost Wolf that each of its predecessors had, and I just didn't feel like waiting for the fixes, arguing with the author again about how macro conditionals work with shapeshifts, and then still dealing with a confusing configuration.

**Roll** was definitely on the to-do list at some point. **PW:S** probably won't be included since it requires a target, or if I did include it, it would only work out of combat and always target the player. **Sprint** will probably require a modifier. Undecided on **Unholy Presence** (and Aspect of the Cheetah/Pack).

**Comment by Phanx** [comment]
Added Blazing Speed and Roll/Chi Torpedo in [this commit](https://github.com/Phanx/MountMe/commit/7c814b2f547a716de9e8351a3a44527012440b51). Not tested yet.

Actually just realized I made them all require the travel form modifier, since I just reused the paladin code and made it general... will have to fix that later.

**Comment by Phanx** [comment]
Added Death's Advance and Sprint as well. All of these abilities with cooldowns require the travel form modifier (default CTRL) but I removed the "only use while already moving or in combat" check.
